### ISSUE TITLE
 diferença entre bloc-pattern(jacobaraujo) e Bloc(felangel)

### ISSUE THREAD

**Issue by WillianNightray** [jacobaraujo7/bloc-pattern#10]
Olá, qual é a diferença entre os plugins bloc-pattern(jacobaraujo) ou o Bloc(felangel)?

Agradeço desde já.

**Comment by Katekko** [comment]
Acho que a maior diferença, me corrija se eu estiver errado, é que no bloc_pattern você utiliza injeção de dependência para acessar nos widgets que você precisa. Achei bem tranquilo a utilização, só que estou tendo alguns problemas para utilizar o plugin, algumas situações estão muito confusas e a documentação não está muito excelente.

Espero que o dono do plugin consiga esclarecer algumas coisas...

**Comment by WillianNightray** [comment]
> Acho que a maior diferença, me corrija se eu estiver errado, é que no bloc_pattern você utiliza injeção de dependência para acessar nos widgets que você precisa. Achei bem tranquilo a utilização, só que estou tendo alguns problemas para utilizar o plugin, algumas situações estão muito confusas e a documentação não está muito excelente.

Uhum.

> Espero que o dono do plugin consiga esclarecer algumas coisas...

Poise, eu também rsrs.

e tbm preciso saber se o plugin continuará recebendo atualizações ao decorrer do tempo, para poder utilizá-lo em um projeto de longo prazo....

**Comment by jacobaraujo7** [comment]
Vai sim. Sujestões e PR estamos a disposição tb, inclusive na documentação.

**Comment by jacobaraujo7** [comment]
A principal diferença está na forma que o provedor modula o código. Vc tem algumas ferramentas a mais, inclusivise em conjunto com outro package chamado Slidy, também mantido pela comunidade do Flutterando.

**Comment by WillianNightray** [comment]
Muito Obrigado pelo esclarecimento.
:smile:
