### ISSUE TITLE
Problema ao iniciar uma tela com bloc

### ISSUE THREAD

**Issue by Katekko** [jacobaraujo7/bloc-pattern#11]
Está acontecendo uma situação estranha.

Código para navegação para a segunda tela:
![image](https://user-images.githubusercontent.com/13632735/62308787-8271d580-b45c-11e9-9cfb-a37f4d439322.png)
![image](https://user-images.githubusercontent.com/13632735/62308802-8867b680-b45c-11e9-9463-619f970ce336.png)

Eu inicio o app, ele vai para tela principal e depois eu tento navegar para uma segunda tela.
Da o seguinte erro: 
![image](https://user-images.githubusercontent.com/13632735/62308990-e98f8a00-b45c-11e9-81d2-00976e1c58b9.png)

Na primeira seta é o primeiro bloc iniciado, a segunda é quando eu navego para a tela seguinte.

Agora entra a parte estranha, na primeira tentativa de abrir a tela da o erro de bad state, na segunda tentativa a tela abre normalmente sem o erro.

Alguma solução?

**Comment by jacobaraujo7** [comment]
fix version 2.3.1
