### ISSUE TITLE
Erro Dispose _BlocProviderListState

### ISSUE THREAD

**Issue by eduardolimaoliveira** [jacobaraujo7/bloc-pattern#2]
No Dispose dos Blocs, a instrução For está errada. Não pode ser <= e sim <, pois está tentando ler um item a mais do que deveria:

Errado: for (int i = 0; i **<=** bloc.length; i++) ...
Correto for (int i = 0; i **<** bloc.length; i++) ...

**Comment by jacobaraujo7** [comment]
fix version 1.5.1
