### ISSUE TITLE
BlocProvider: Module "global" is not in the widget tree

### ISSUE THREAD

**Issue by ivanportales** [jacobaraujo7/bloc-pattern#23]
Então, sou novato em Flutter e tô aprendendo Bloc, tá dando esse erro que eu não faço idéia do pq, não sei se esse  é o lugar certo de fazer essas perguntas de noob mas queria essa força pra continuar nos estudos kk , segue os prints do erro e do meu código.
![erro](https://user-images.githubusercontent.com/55515254/67261486-3b054f00-f477-11e9-86fd-fb8d86a6ccc4.png)
Código do MyApp, onde eu coloco o meu Bloc com o intuito de ser acessado globalmente pela app
![main](https://user-images.githubusercontent.com/55515254/67261504-4eb0b580-f477-11e9-9516-972f68b022c2.png)
Código do meu Bloc
![bloc](https://user-images.githubusercontent.com/55515254/67261531-6f790b00-f477-11e9-963d-aab32e258bf5.png)
A linha de código da chamada da instância do meu bloc
![chamada](https://user-images.githubusercontent.com/55515254/67261552-8f103380-f477-11e9-8418-e051ec4a1f93.png)

**Comment by Katekko** [comment]
Consegue disponibilizar o projeto pra eu rodar na minha maquina? Tenta reproduzir o bug com todo o codigo em um mesmo arquivo, ai coloca o arquivo no gist e passa pra ca.

**Comment by ivanportales** [comment]
o repositório do projeto github.com/ivanportales/flutterbloc, vlw pela atenção aí brother

**Comment by ivanportales** [comment]
Nossa senhora, agora que eu me toquei que a gente pega a instância dentro da função build do Widget.
No meu caso, eu tava pegando fora da função, botando como um atributo do Widget. Despois da mudança, de pegar a instancia na função build do Widget, solucionou o problema. Desculpa pelo incômodo aí, erro de noob msm.

**Comment by jacobaraujo7** [comment]
Fechando a theread aqui. Mas se aparecer outras coisas nos avise :)
