### ISSUE TITLE
Erro ao voltar para uma tela que usa o mesmo bloc: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by guilhermeof** [jacobaraujo7/bloc-pattern#25]
Eu tenho um bloc_login, eu uso ele em uma página onde o usuário vai selecionar o seu ambiente de estudo e após ele fazer isso é redirecionado para tela de login, aí quando eu tento retornar para a tela de seleção de ambientes, selecionar o ambiente de estudo para redirecionar para tela de login apresenta o seguinte erro: 
Bad state: Cannot add new events after calling close

Fluxo no qual apresenta o erro:
1 - Na tela de ambientes de estudo o usuário seleciona o ambiente e é redirecionado para tela de login (Nesse momento é usado o login_bloc onde tem uma função para poder salvar o ambiente de estudo)
2 - Na tela de login é resgatado o ambiente de estudo selecionado na tela anterior através do login_bloc
3 - Quando é retornado para tela de ambientes de estudo e selecionado novamente um abiente é exibido o erro relatado acima.

**Comment by jacobaraujo7** [comment]
Você pode fornecer algumas informações a mais.
- versão do bloc_pattern
- Log de erro
