### ISSUE TITLE
trouble with name

### ISSUE THREAD

**Issue by huang12zheng** [jacobaraujo7/bloc-pattern#26]
* it is just some my options

```dart
abstract class ModuleWidget extends StatelessWidget {
  List<Bloc> get blocs;
  List<Dependency> get dependencies;
  Widget get view;

  Inject get inject => BlocProvider.tag(this.runtimeType.toString());

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      tagText: this.runtimeType.toString(),
      blocs: blocs,
      dependencies: dependencies,
      child: view,
    );
  }
}

```
Bloc is InjectToBlocAdapter
BlocProvider is ModuleProvider

---

|GlueClass| GlueProvider|obj|objClass| Cache|key|
|-|-|-|-|-|-|
|Module|~~BlocProvider~~ModuleProvider|core|Core|_injectMap|ModuleType|
|~~Bloc~~InjectToBlocAdapter|nothing| bloc| Bloc or Provider |core._injectMapBloc| bloc.toString()|

**Comment by jacobaraujo7** [comment]
Thanks for the sugestion.
We are working on an object provider based on named routes. Take a look at flutter_modular
https://github.com/Flutterando/modular

**Comment by huang12zheng** [comment]
close with modular is better
