### ISSUE TITLE
Problema no  BlocProvider.getBloc() quando Navigator.pushAndRemoveUntil

### ISSUE THREAD

**Issue by rodrigorahman** [jacobaraujo7/bloc-pattern#6]
Quando tento recuperar o bloc do provider (BlocProvider.getBloc<ChatBloc>()) em uma pagina que veio de um Navigator.pushAndRemoveUntil ele me apresenta o erro abaixo.

Unhandled Exception: NoSuchMethodError: The method 'bloc' was called on null.
E/flutter (14178): Receiver: null
E/flutter (14178): Tried calling: bloc<ChatBloc>(null)

Alterei para Navigator.push e funcionou corretamente.

**Comment by jacobaraujo7** [comment]
Olá.
Você pode nos informar mais informações, como a versão do Flutter, a versão do bloc_pattern e os trechos de códigos relacionado a sua dúvida?

**Comment by rodrigorahman** [comment]
bloc_pattern: ^2.2.3

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

O erro acontece quando navego para a pagina: 

```
Navigator.pushAndRemoveUntil(
              context,
              MaterialPageRoute(
                  builder: (BuildContext context) => ChatPage(chatId)), (ctx) => false);
```

Na pagina em: 

```
initState() {
    super.initState();
     chatBloc = BlocProvider.getBloc<ChatBloc>();
     chatBloc.inChat.add(ChatModel());
}
```

Bloc: 

```

import 'package:ToaToa/domain/chat_model.dart';
import 'package:bloc_pattern/bloc_pattern.dart';
import 'package:rxdart/rxdart.dart';

class ChatBloc extends BlocBase {

  var _chatController = BehaviorSubject<ChatModel>();

  Stream<ChatModel> get outChat => _chatController.stream;
  Sink<ChatModel> get inChat => _chatController.sink;

  updateChat(chat){
    this.inChat.add(chat);
  }


  @override
  void dispose() {
    _chatController.close();
    super.dispose();
  }


}
```

na main.dart

```
@override
  Widget build(BuildContext context) {
    var config = AppConfig.of(context);
    return BlocProvider(
      blocs: [
        Bloc((i) => ChatBloc()),
      ],
      child: Consumer<ProfileBloc>(
        builder: (context, bloc) {
          return StreamBuilder<UserModel>(
              stream: bloc.outProfile,
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  return Material(child: HomeMaps());
                } else {
                  return Material(child: Home());
                }
              });
        },
      ),
    );
  }
```

**Comment by jacobaraujo7** [comment]
Vc está usando o MaterialApp aonde?

**Comment by rodrigorahman** [comment]
No start do projeto no main do runApp():

![image](https://user-images.githubusercontent.com/20157178/61675600-5d989800-accf-11e9-9a67-9f00efb149ff.png)

**Comment by rodrigorahman** [comment]
![image](https://user-images.githubusercontent.com/20157178/61675641-8a4caf80-accf-11e9-835d-542d3a562445.png)

**Comment by rodrigorahman** [comment]
Fechei por engano

**Comment by jacobaraujo7** [comment]
Estou tentando reproduzir o erro mas acaba não dando o erro. Vc pode fazer um pequeno exemplo e publicar no github para que eu possa está analisando?
Qualquer coisa estou no Flutterando tb

**Comment by Yodart** [comment]
Estou com o mesmo erro, acredito que tenha algo relacionado com a navegacao entre paginas, por algum motivo o bloc perde state e retorna null quando voce navega para um nova pagina e depois volta.

**Comment by rodrigorahman** [comment]
@jacobaraujo7 Percebi que isso ocorre quando vc está em alguma navegação ex: 
Estou no Main -> fui para Login -> Fiz o pushAndRemoveUntil para home. 

Pronto ai o problema acontece.

Não sei se ajuda, vou tentar hoje montar o projeto e postar no github com o problema

**Comment by jacobaraujo7** [comment]
Sim, quando trabalhamos com navegação, ele subistitui na arvore de elementos do MaterialApp, ou seja, a cada novo push o widget na home é alterado. O pushAndRemoveUntil em teoria nao deveria interferir nisso.

**Comment by jacobaraujo7** [comment]
fechei por engano tb. my bad

**Comment by Katekko** [comment]
Se eu navego com replacement para própria página que está com o provider ele cria um e da dispose no antigo(provavelmente).
![image](https://user-images.githubusercontent.com/13632735/62292676-4bd89280-b43d-11e9-9220-74b0016553a8.png)

E quando eu tento navegar para outra página que precisa do bloc da um erro. 
`The method 'bloc' was called on null`
O que significa que a referência do meu bloc foi perdida ao navegar para propria pagina via pushReplacementNamed.

**Comment by rodrigorahman** [comment]
@jacobaraujo7 Desculpe a demora, conforme solicitado segue o projeto que apresenta o problema: 

https://github.com/rodrigorahman/bloc_pattern_example_error

Qualquer dúvida estou a disposição.

**Comment by Katekko** [comment]
Só falta essa issue para eu usar a lib por completo. O problema que eu identifiquei é que quando ele sai em de uma tela que implementa o mesmo bloc, ao sair ele dá dispose e parece que não consigo mais ativar. Algo assim teria que verificar mais a fundo. A lib é simples e perfeita, eu gostaria de continuar usando ela nos meus projetos...

**Comment by jacobaraujo7** [comment]
Fix version 2.3.1

**Comment by magnocasmor** [comment]
Estou usando a versão 2.3.3 e este erro continua acontecendo quando:

- Estou no `Module A`

- Dou pop no `Module A`. 

- Na rota atual, o `Future` de navegação conclui e ai dou push novamente em `Module A`

Pelo o que entendi, o push reinstancia o `Module A` antes mesmo do dispose ser chamado quando realiza o pop emitindo o mesmo erro `The method 'bloc' was called on null`
