### ISSUE TITLE
Problema ao utilizar pushReplacementNamed com BLOC

### ISSUE THREAD

**Issue by Katekko** [jacobaraujo7/bloc-pattern#8]
Eu estou tentando navegar pra uma pagina que utiliza o mesmo BLOC da pagina anterior, só que eu navego pelas páginas com pushReplacementNamed (essas duas paginas). Quando ele vai tentar acessar o bloc da outra página aparece que foi chamado o close do bloc e então não é possível chamar os métodos.

E sim, não existe nenhuma tela antes na stack. Elas duas são as telas principais, quando entra pode cair em uma ou na outra e normalmente pode-se navegar entre as duas por pushReplacementNamed. Eu estou usando a lib de um jeito ruim ou da para fazer alguma outra coisa?

![image](https://user-images.githubusercontent.com/13632735/62129021-0769bd00-b2ac-11e9-8486-777348c4e795.png)

Nessa situação o que eu posso fazer? 

Edt: Um workaround foi eu colocar um widget superior como root e a partir dele eu faço minhas transições de tela, ai sempre o meu bloc vai estar ativo. Mas acho isso é errado pois existem telas q eu nao vou precisar do bloc e ele vai ainda sim estar ativo. Deveria ter algum jeito de manter a persistência do bloc mesmo ao navegar com replacement. Ou está acontecendo alguma coisa que eu não consigo identificar.

**Comment by jacobaraujo7** [comment]
Estamos lidando com isso aqui #6
