### ISSUE TITLE
Descrever melhor o problema acontecido: Bad State: No element

### ISSUE THREAD

**Issue by Katekko** [jacobaraujo7/bloc-pattern#9]
Por favor, teria como deixar mais explícito o que está acontecendo aqui nesse erro?

![image](https://user-images.githubusercontent.com/13632735/62147276-8e7b5d00-b2cd-11e9-8be8-52dc8040afd1.png)

**Comment by jacobaraujo7** [comment]
Tem sim, vamos deixar trabalha no tratamento de erros em breve.
